In [10]:
import pandas as pd
import geopandas as gpd

In [11]:
#read in both pick up and drop off dataframes
pickup = pd.read_csv('pickup_vol.csv')
dropoff = pd.read_csv('dropoff_vol.csv')

In [15]:
total = pd.merge(pickup,dropoff,how='outer',left_on='PULocationID',right_on='DOLocationID')
total = total[['PULocationID','night_counts_x','day_counts_x','night_prop_x','night_counts_y','day_counts_y','night_prop_y']]
total.fillna(0,inplace=True)
total.head()

,PULocationID,night_counts_x,day_counts_x,night_prop_x,night_counts_y,day_counts_y,night_prop_y
0,0.0,3263236.0,2.023988e+07,0.138843,0.0,0.0,0.000000
1,1.0,353187224.0,1.710415e+09,0.171151,814.0,21047.0,0.037235
2,2.0,82635893.0,3.385405e+08,0.196203,363.0,1030.0,0.260589
3,3.0,22778936.0,9.493858e+07,0.193505,4532.0,22130.0,0.169980
4,4.0,11174684.0,4.417780e+07,0.201882,1761922.0,3521227.0,0.333498

In [18]:
total.rename(columns={'night_counts_x':'PU_night','day_counts_x':'PU_day','night_prop_x':'PU_prop','night_counts_y':'DO_night','day_counts_y':'DO_day','night_prop_y':'DO_prop'},inplace=True)

In [19]:
total.columns

Index(['PULocationID', 'PU_night', 'PU_day', 'PU_prop', 'DO_night', 'DO_day',
       'DO_prop'],
      dtype='object')

In [20]:
total['total_night'] = total['PU_night'] + total['DO_night'] 
total['total_day'] = total['PU_day'] + total['DO_day'] 
total['total_prop'] = total['total_night'] / (total['total_night'] + total['total_day'])

In [3]:
taxi_geo = gpd.read_file('taxi_zones.shp')

In [4]:
taxi_geo.head()

,OBJECTID,Shape_Leng,Shape_Area,zone,LocationID,borough,geometry
0,1,0.116357,0.000782,Newark Airport,1,EWR,"POLYGON ((933100.9183527103 192536.0856972019,..."
1,2,0.433470,0.004866,Jamaica Bay,2,Queens,"(POLYGON ((1033269.243591294 172126.0078125, 1..."
2,3,0.084341,0.000314,Allerton/Pelham Gardens,3,Bronx,"POLYGON ((1026308.769506663 256767.6975403726,..."
3,4,0.043567,0.000112,Alphabet City,4,Manhattan,"POLYGON ((992073.4667968601 203714.0759887695,..."
4,5,0.092146,0.000498,Arden Heights,5,Staten Island,"POLYGON ((935843.3104932606 144283.335850656, ..."

In [5]:
pickup.head()

   Unnamed: 0  PULocationID  night_counts    day_counts  night_prop
0           0             0     3263236.0  2.023988e+07    0.138843
1           1             1   353187224.0  1.710415e+09    0.171151
2           2             2    82635893.0  3.385405e+08    0.196203
3           3             3    22778936.0  9.493858e+07    0.193505
4           4             4    11174684.0  4.417780e+07    0.201882

In [6]:
pickup_geo = pd.merge(taxi_geo,pickup,how='left',left_on='LocationID',right_on='PULocationID')
pickup_geo.head()

,OBJECTID,Shape_Leng,Shape_Area,zone,LocationID,borough,geometry,Unnamed: 0,PULocationID,night_counts,day_counts,night_prop
0,1,0.116357,0.000782,Newark Airport,1,EWR,"POLYGON ((933100.9183527103 192536.0856972019,...",1.0,1.0,353187224.0,1.710415e+09,0.171151
1,2,0.433470,0.004866,Jamaica Bay,2,Queens,"(POLYGON ((1033269.243591294 172126.0078125, 1...",2.0,2.0,82635893.0,3.385405e+08,0.196203
2,3,0.084341,0.000314,Allerton/Pelham Gardens,3,Bronx,"POLYGON ((1026308.769506663 256767.6975403726,...",3.0,3.0,22778936.0,9.493858e+07,0.193505
3,4,0.043567,0.000112,Alphabet City,4,Manhattan,"POLYGON ((992073.4667968601 203714.0759887695,...",4.0,4.0,11174684.0,4.417780e+07,0.201882
4,5,0.092146,0.000498,Arden Heights,5,Staten Island,"POLYGON ((935843.3104932606 144283.335850656, ...",5.0,5.0,24868953.0,1.048731e+08,0.191680

In [8]:
dropoff_geo = pd.merge(taxi_geo,dropoff,how='left',left_on='LocationID',right_on='DOLocationID')
dropoff_geo.head()

,OBJECTID,Shape_Leng,Shape_Area,zone,LocationID,borough,geometry,Unnamed: 0,DOLocationID,night_counts,day_counts,night_prop
0,1,0.116357,0.000782,Newark Airport,1,EWR,"POLYGON ((933100.9183527103 192536.0856972019,...",0.0,1.0,814.0,21047.0,0.037235
1,2,0.433470,0.004866,Jamaica Bay,2,Queens,"(POLYGON ((1033269.243591294 172126.0078125, 1...",1.0,2.0,363.0,1030.0,0.260589
2,3,0.084341,0.000314,Allerton/Pelham Gardens,3,Bronx,"POLYGON ((1026308.769506663 256767.6975403726,...",2.0,3.0,4532.0,22130.0,0.169980
3,4,0.043567,0.000112,Alphabet City,4,Manhattan,"POLYGON ((992073.4667968601 203714.0759887695,...",3.0,4.0,1761922.0,3521227.0,0.333498
4,5,0.092146,0.000498,Arden Heights,5,Staten Island,"POLYGON ((935843.3104932606 144283.335850656, ...",4.0,5.0,10.0,493.0,0.019881

In [23]:
total_geo = pd.merge(taxi_geo,total,how='left',left_on='LocationID',right_on='PULocationID')

In [9]:
pickup_geo.to_file(driver='ESRI Shapefile',filename='pickup')
dropoff_geo.to_file(driver='ESRI Shapefile',filename='dropoff')

In [24]:
total_geo.to_file(driver='ESRI Shapefile',filename='total')